### ISSUE TITLE
Convert community-id into BPF or original 5 tuple

### ISSUE THREAD

**Issue by swish-cto** [corelight/pycommunityid#1] opened 2019-08-19 15:03 UTC
Desire a script which will convert a community-id into the following formats for use with systems which don't support a community-id:
- Berkeley Packet Filter expression
- original 5 tuple

**Comment by ckreibich** [comment] 2020-09-14 20:49
Interesting request, thank you. The current version of Community ID isn't reversible — you cannot go from the hash back to the input tuple. That was by design, though I can see why this would be handy. I'll add a note to the spec itself at https://github.com/corelight/community-id-spec as a feature request, linking to yours, and close this one.

(Apologies for the glacial response time!)

**Closed as completed by ckreibich** 2020-09-14 20:49 UTC
